### ISSUE TITLE
Error: File.publicURL provided incorrect OutputType: 'String'

### ISSUE THREAD

**Issue by psamim** [pedronauck/docz#1641]
## Bug Report

I added Docz to an existing React project. Running `docz build `and `docz dev` returns the error:

```
Error: File.publicURL provided incorrect OutputType: 'String'
``` 

There is an additional stack trace in `docz dev`:

```
Missing onError handler for invocation 'building-schema', error was 'Error: File.publicURL provided incorrect OutputType: 'String''. Stacktrace was 'Error: File.publicURL provided incorrect OutputType: 'String'
    at TypeMapper.convertOutputFieldConfig (/home/samim/workspace/global/gworld-sspa/apps/social/node_modules/graphql-compose/lib/TypeMapper.js:294:15)
    at resolveOutputConfigAsThunk (/home/samim/workspace/global/gworld-sspa/apps/social/node_modules/graphql-compose/lib/utils/configAsThunk.js:19:41)
    at ObjectTypeComposer.getFieldConfig (/home/samim/workspace/global/gworld-sspa/apps/social/node_modules/graphql-compose/lib/ObjectTypeComposer.js:300:58)
    at /home/samim/workspace/global/gworld-sspa/apps/social/node_modules/graphql-compose/lib/utils/toInputObjectType.js:44:19
    at Array.forEach (<anonymous>)
    at toInputObjectType (/home/samim/workspace/global/gworld-sspa/apps/social/node_modules/graphql-compose/lib/utils/toInputObjectType.js:38:14)
    at ObjectTypeComposer.getInputTypeComposer (/home/samim/workspace/global/gworld-sspa/apps/social/node_modules/graphql-compose/lib/ObjectTypeComposer.js:600:84)
    at getSortInput (/home/samim/workspace/global/gworld-sspa/apps/social/node_modules/gatsby/src/schema/types/sort.ts:152:42)
    at addTypeToRootQuery (/home/samim/workspace/global/gworld-sspa/apps/social/node_modules/gatsby/src/schema/schema.js:1133:23)
    at processTypeComposer (/home/samim/workspace/global/gworld-sspa/apps/social/node_modules/gatsby/src/schema/schema.js:216:13)
    at async Promise.all (index 13)
    at updateSchemaComposer (/home/samim/workspace/global/gworld-sspa/apps/social/node_modules/gatsby/src/schema/schema.js:171:3)
    at buildSchema (/home/samim/workspace/global/gworld-sspa/apps/social/node_modules/gatsby/src/schema/schema.js:62:3)
    at build (/home/samim/workspace/global/gworld-sspa/apps/social/node_modules/gatsby/src/schema/index.js:105:18)
    at buildSchema (/home/samim/workspace/global/gworld-sspa/apps/social/node_modules/gatsby/src/services/build-schema.ts:19:3)'
```

**Environment**

- docz version: 2.3.1
- OS: Archlinux
- Node/npm version: [e.g. Node 8/npm 5] Node 16.3.0, NPM 7.17.0

**Comment by NightFox7** [comment]
I have the same issue. @psamim did you find a workaround ?

**Comment by fxneel** [comment]
I have the same error with "gatsby": "^2.13.27" and react 0.71
