### ISSUE TITLE
Error parsing respository URLs

### ISSUE THREAD

**Issue by wldcordeiro** [pedronauck/docz#217]
## Bug Report

**Describe the bug**

Repo URL failure?

Add a repository to your package.json

```
 "repository": {
    "type": "git",
    "url": "https://gitlab.com/group/repo"
  },
```

```shell
$ docz dev
✖  fatal     Failed to process your server: TypeError: Cannot read property 'replace' of undefined
    at getRepoEditUrl (/Users/wellingtoncordeiro/Documents/projects/cnc/citadel/node_modules/docz-core/dist/index.js:1:7669)
    at new Entries (/Users/wellingtoncordeiro/Documents/projects/cnc/citadel/node_modules/docz-core/dist/index.js:1:8668)
    at state (/Users/wellingtoncordeiro/Documents/projects/cnc/citadel/node_modules/docz-core/dist/index.js:1:9528)
    at Object.dev (/Users/wellingtoncordeiro/Documents/projects/cnc/citadel/node_modules/docz-core/dist/index.js:1:24679)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
error Command failed with exit code 1.

```

**Expected behavior**

Expected dev server to start without error

**Comment by wldcordeiro** [comment]
Also tried setting the repo to an SSH URL `git@gitlab.com:group/repo.git` and still see the error.

**Comment by jiangkk** [comment]
Did you fix it ?  I get same problem

**Comment by wldcordeiro** [comment]
No, I have not been able to fix it.

**Comment by pedronauck** [comment]
Fixed on [v0.10.3](https://github.com/pedronauck/docz/releases/tag/v0.10.3)

**Comment by wldcordeiro** [comment]
@pedronauck I was hoping we could find out the source I'd love to be able to get links back to my gitlab repo.

**Comment by pedronauck** [comment]
@wldcordeiro I'm tried using a `package.json` as above and everything worked as well

```
{
  repository: {
    type: "git",
    url: "git@gitlab.com:some/repo"
  }
}
```

Which version of node you're using? We are using [get-pkg-repo](https://github.com/stevemao/get-pkg-repo) to parse repository info from `package.json`, maybe can be some error from there!
