### ISSUE TITLE
Dev server crash

### ISSUE THREAD

**Issue by wldcordeiro** [pedronauck/docz#220]
## Bug Report

**To Reproduce**

1. Run `yarn docz dev`

doczrc.js

```js
const { babel } = require('docz-plugin-babel6');

module.exports = {
  title: 'CNC Citadel',
  description: 'The home for CNC projects.',
  plugins: [babel()],
};
```

```shell
citadel on  publish-fixes [!] is 📦 ⚠ via ⬢ v9.11.1
[I] ➜ yarn start
yarn run v1.9.4
$ docz dev


 ERROR  Failed to compile with 1 errors                                                                                        19:43:49

 error  in ./.docz/app/index.jsx

Module build failed (from ./node_modules/happypack/loader.js):
Error: Plugin/Preset files are not allowed to export objects, only functions. In /Users/wellingtoncordeiro/Documents/projects/cnc/citadel/node_modules/babel-preset-react-app/index.js
    at createDescriptor (/Users/wellingtoncordeiro/Documents/projects/cnc/citadel/node_modules/docz-core/node_modules/@babel/core/lib/config/config-descriptors.js:138:11)
    at items.map (/Users/wellingtoncordeiro/Documents/projects/cnc/citadel/node_modules/docz-core/node_modules/@babel/core/lib/config/config-descriptors.js:69:50)
    at Array.map (<anonymous>)
    at createDescriptors (/Users/wellingtoncordeiro/Documents/projects/cnc/citadel/node_modules/docz-core/node_modules/@babel/core/lib/config/config-descriptors.js:69:29)
    at createPresetDescriptors (/Users/wellingtoncordeiro/Documents/projects/cnc/citadel/node_modules/docz-core/node_modules/@babel/core/lib/config/config-descriptors.js:61:10)
    at passPerPreset (/Users/wellingtoncordeiro/Documents/projects/cnc/citadel/node_modules/docz-core/node_modules/@babel/core/lib/config/config-descriptors.js:53:96)
    at cachedFunction (/Users/wellingtoncordeiro/Documents/projects/cnc/citadel/node_modules/docz-core/node_modules/@babel/core/lib/config/caching.js:32:19)
    at presets.presets (/Users/wellingtoncordeiro/Documents/projects/cnc/citadel/node_modules/docz-core/node_modules/@babel/core/lib/config/config-descriptors.js:25:84)
    at mergeChainOpts (/Users/wellingtoncordeiro/Documents/projects/cnc/citadel/node_modules/docz-core/node_modules/@babel/core/lib/config/config-chain.js:303:26)
    at /Users/wellingtoncordeiro/Documents/projects/cnc/citadel/node_modules/docz-core/node_modules/@babel/core/lib/config/config-chain.js:266:7

 @ multi ./node_modules/docz-core/node_modules/babel-polyfill/lib/index.js ./.docz/app/index.jsx



 WAIT  Compiling...                                                                                                            19:43:49



 ERROR  Failed to compile with 1 errors                                                                                        19:43:50

 error  in ./.docz/app/index.jsx

Module build failed (from ./node_modules/happypack/loader.js):
Error: Plugin/Preset files are not allowed to export objects, only functions. In /Users/wellingtoncordeiro/Documents/projects/cnc/citadel/node_modules/babel-preset-react-app/index.js
    at createDescriptor (/Users/wellingtoncordeiro/Documents/projects/cnc/citadel/node_modules/docz-core/node_modules/@babel/core/lib/config/config-descriptors.js:138:11)
    at items.map (/Users/wellingtoncordeiro/Documents/projects/cnc/citadel/node_modules/docz-core/node_modules/@babel/core/lib/config/config-descriptors.js:69:50)
    at Array.map (<anonymous>)
    at createDescriptors (/Users/wellingtoncordeiro/Documents/projects/cnc/citadel/node_modules/docz-core/node_modules/@babel/core/lib/config/config-descriptors.js:69:29)
    at createPresetDescriptors (/Users/wellingtoncordeiro/Documents/projects/cnc/citadel/node_modules/docz-core/node_modules/@babel/core/lib/config/config-descriptors.js:61:10)
    at passPerPreset (/Users/wellingtoncordeiro/Documents/projects/cnc/citadel/node_modules/docz-core/node_modules/@babel/core/lib/config/config-descriptors.js:53:96)
    at cachedFunction (/Users/wellingtoncordeiro/Documents/projects/cnc/citadel/node_modules/docz-core/node_modules/@babel/core/lib/config/caching.js:32:19)
    at presets.presets (/Users/wellingtoncordeiro/Documents/projects/cnc/citadel/node_modules/docz-core/node_modules/@babel/core/lib/config/config-descriptors.js:25:84)
    at mergeChainOpts (/Users/wellingtoncordeiro/Documents/projects/cnc/citadel/node_modules/docz-core/node_modules/@babel/core/lib/config/config-chain.js:303:26)
    at /Users/wellingtoncordeiro/Documents/projects/cnc/citadel/node_modules/docz-core/node_modules/@babel/core/lib/config/config-chain.js:266:7
    at buildRootChain (/Users/wellingtoncordeiro/Documents/projects/cnc/citadel/node_modules/docz-core/node_modules/@babel/core/lib/config/config-chain.js:56:29)
    at loadPrivatePartialConfig (/Users/wellingtoncordeiro/Documents/projects/cnc/citadel/node_modules/docz-core/node_modules/@babel/core/lib/config/partial.js:55:55)
    at Object.loadPartialConfig (/Users/wellingtoncordeiro/Documents/projects/cnc/citadel/node_modules/docz-core/node_modules/@babel/core/lib/config/partial.js:80:18)
    at Object.<anonymous> (/Users/wellingtoncordeiro/Documents/projects/cnc/citadel/node_modules/docz-core/node_modules/babel-loader/lib/index.js:82:26)
    at Generator.next (<anonymous>)
    at step (/Users/wellingtoncordeiro/Documents/projects/cnc/citadel/node_modules/docz-core/node_modules/babel-loader/lib/index.js:3:221)

 @ multi ./node_modules/docz-core/node_modules/babel-polyfill/lib/index.js ./.docz/app/index.jsx
```

**Expected behavior**

Dev server starts up like normal

**Environment**

* OS: OSX  10.13.1
* Node/npm version: Node 9.11.1, yarn 1.9.4

**Comment by mdugue** [comment]
same here… any news on this?

**Comment by pedronauck** [comment]
I'm working on this fix, but is very hard to find a solution 😕

**Comment by wldcordeiro** [comment]
FYI this seems to be something to do with babel6 plugin. I made the upgrade to 7 for my project and the problem went away (hooray RC stage 😄 for babel.)

**Comment by pedronauck** [comment]
Yes, the best thing, in this case, is updated to new version of babel since docz was entirely built around it. But to keep doing compatibility I think that this need to be fixed so far 😖

**Comment by pedronauck** [comment]
Last night I spend a lot of hours trying to fix that but I can't figure out what's happening. Before [this commit](436c742d37cd0f83c66504aaf99731ae6d173914) everything was working good with babel 6, after that this bug came up. There was a commit updating babel dependencies to new `7.0.0-rc.1` and I thought it's the problem, I made a rebase removing the commit but the bug still there.

I did a lot of things like remove `yarn.lock` keeping just the oldest version of babel 7, split babel configuration in a preset, keep both in separate packages, but even using `docz-plugin-babel6` I don't know why when webpack starts it's keeping using `@babel/core` instead of `babel-core`.

Some help here will be awesome since this bug is breaking my head 😕 

@hzoo maybe you can help us?

**Comment by jiangkk** [comment]
same here… any news on this?

**Comment by drmzio** [comment]
Same issue here. Tried updating babel but still shows error.

**Comment by mzabriskie** [comment]
@pedronauck I am experiencing the same issue. After some tinkering I noticed that this only happens when I have a `.babelrc` in the root directory that defines presets. Hopefully this helps narrow things down some.

**Comment by jiangkk** [comment]
use  `docz` version 0.9.6  and  `docz-plugin-babel6` .....    can  solve it

**Comment by pedronauck** [comment]
In the [new release](https://github.com/pedronauck/docz/releases/tag/v0.11.0) and since [Babel 7 now is a reality](https://babeljs.io/blog/2018/08/27/7.0.0), we're dropping support for older versions of babel. Please, if you want to use docz new version, upgrade your babel. You can use [babel-upgrade](https://github.com/babel/babel-upgrade) by just running:

```jsx
npx babel-upgrade --write
```
