### ISSUE TITLE
Can't start dev server - babel-preset-react error

### ISSUE THREAD

**Issue by whoisryosuke** [pedronauck/docz#304]
## Bug Report

Installed Docz. Created MDX file. Ran Docz dev. Receive error.

**To Reproduce**

1. [Clone my repo](https://github.com/whoisryosuke/design-system-jss/tree/feat/docz)
1. `npm run docs`

1. Install Docz `npm i docz -D` on [pre-existing project](https://github.com/whoisryosuke/design-system-jss/)
1. Add to scripts package.json
1. Ran `docz dev`
1. Loads nearly completely
1. See error

```shell
Module build failed (from ./node_modules/happypack/loader.js):
Error: Plugin/Preset files are not allowed to export objects, only functions. In /Volumes/WEEDPORNDAILY/Development/React/design-syste
m-jss/node_modules/babel-preset-react/lib/index.js
    at createDescriptor (/Volumes/WEEDPORNDAILY/Development/React/design-system-jss/node_modules/@babel/core/lib/config/config-descrip
tors.js:178:11)
    at items.map (/Volumes/WEEDPORNDAILY/Development/React/design-system-jss/node_modules/@babel/core/lib/config/config-descriptors.js
:109:50)
    at Array.map (<anonymous>)
    at createDescriptors (/Volumes/WEEDPORNDAILY/Development/React/design-system-jss/node_modules/@babel/core/lib/config/config-descri
ptors.js:109:29)
    at createPresetDescriptors (/Volumes/WEEDPORNDAILY/Development/React/design-system-jss/node_modules/@babel/core/lib/config/config-descriptors.js:101:10)
    at passPerPreset (/Volumes/WEEDPORNDAILY/Development/React/design-system-jss/node_modules/@babel/core/lib/config/config-descriptors.js:58:96)
    at cachedFunction (/Volumes/WEEDPORNDAILY/Development/React/design-system-jss/node_modules/@babel/core/lib/config/caching.js:33:19)
    at presets.presets (/Volumes/WEEDPORNDAILY/Development/React/design-system-jss/node_modules/@babel/core/lib/config/config-descriptors.js:29:84)
    at mergeChainOpts (/Volumes/WEEDPORNDAILY/Development/React/design-system-jss/node_modules/@babel/core/lib/config/config-chain.js:315:26)
    at /Volumes/WEEDPORNDAILY/Development/React/design-system-jss/node_modules/@babel/core/lib/config/config-chain.js:278:7
    at buildRootChain (/Volumes/WEEDPORNDAILY/Development/React/design-system-jss/node_modules/@babel/core/lib/config/config-chain.js:68:29)
    at loadPrivatePartialConfig (/Volumes/WEEDPORNDAILY/Development/React/design-system-jss/node_modules/@babel/core/lib/config/partial.js:57:55)
    at Object.loadPartialConfig (/Volumes/WEEDPORNDAILY/Development/React/design-system-jss/node_modules/@babel/core/lib/config/partial.js:82:18)
    at Object.<anonymous> (/Volumes/WEEDPORNDAILY/Development/React/design-system-jss/node_modules/docz-core/node_modules/babel-loader/lib/index.js:105:26)
    at Generator.next (<anonymous>)
    at step (/Volumes/WEEDPORNDAILY/Development/React/design-system-jss/node_modules/docz-core/node_modules/babel-loader/lib/index.js:3:221)

 @ multi ./node_modules/@babel/polyfill/lib/index.js ./.docz/app/index.jsx
```

Here's a link to my repo's Docz branch:
https://github.com/whoisryosuke/design-system-jss/tree/feat/docz

**Expected behavior**

Dev server to actually run.

**Environment**

* OS: OSX 10.13.4
* Node/npm version: Node 9 / NPM 6.4.0

**Additional context/Screenshots**

I ended up at this issue:
https://github.com/pedronauck/docz/issues/300

I noticed that I didn't have the latest version of Babel (like recommended by some users). I replaced my old Babel with all Babel 7 packages, and I still received the error.

**Comment by pedronauck** [comment]
@whoisryosuke this happen because we have some babel plugin/preset that's using an older version of babel, deleting your `node_moduels` or `yarn.lock` can resolve this maybe... If this doesn't fix your bug, try to see if the version of your `babel-preset-react` is using babel 7 🙏

**Comment by whoisryosuke** [comment]
@pedronauck Good advice. Fixed it!

1. Nuked `node_modules`
1. `npm i`
1. And probably the coup-de-grace: Updating `.babelrc` with the new preset definitions (`@babel/preset-env` vs `env`).
