### ISSUE TITLE
TypeError: Cannot read property 'bindings' of null

### ISSUE THREAD

**Issue by Pierre-RA** [pedronauck/docz#33]
## Bug Report

**Describe the bug**

After installing `docz`, I tried to give a go with the following command:

```
$ docz dev
```

and I got the following error:

```shell
 error  in ./.docz/app/index.jsx
Module build failed (from ./node_modules/happypack/loader.js):
TypeError: Cannot read property 'bindings' of null
    at Scope.moveBindingTo (/***/node_modules/docz-core/node_modules/@babel/traverse/lib/scope/index.js:869:13)
    at convertBlockScopedToVar (/***/node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:139:13)
    at PluginPass.VariableDeclaration (/***/node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:26:9)
    at newFn (/***/node_modules/docz-core/node_modules/@babel/traverse/lib/visitors.js:193:21)
    at NodePath._call (/***/node_modules/docz-core/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/***/node_modules/docz-core/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/***/node_modules/docz-core/node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (/***/node_modules/docz-core/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitMultiple (/***/node_modules/docz-core/node_modules/@babel/traverse/lib/context.js:85:17)
    at TraversalContext.visit (/***/node_modules/docz-core/node_modules/@babel/traverse/lib/context.js:144:19)

 @ multi ./node_modules/babel-polyfill/lib/index.js ./.docz/app/index.jsx
```

**Enviroment**

* OS: [e.g. OSX 10.13.4, Windows 10] Windows 10 and WSL Ubuntu.
* Node/npm version: [e.g. Node 8/npm 5] v10.3.0 / 6.1.0

**Comment by Pierre-RA** [comment]
I can give you the list of babel packages I've found in `node_modules` with the hope it can help.
- babel-code-frame
- babel-core
- babel-generator
- babel-helpers
- babel-jest
- babel-messages
- babel-plugin-emotion
- babel-plugin-inline-dotenv
- babel-plugin-istanbul
- babel-plugin-jest-hoist
- babel-plugin-macros
- babel-plugin-react-docgen
- babel-plugin-syntax-dynamic-import
- babel-plugin-syntax-jsx
- babel-plugin-syntax-object-rest-spread
- babel-plugin-transform-dynamic-import
- babel-plugin-transform-react-remove-prop-types
- babel-polyfill
- babel-preset-jest
- babel-preset-react-app
- babel-register
- babel-runtime
- babel-template
- babel-traverse
- babel-types

**Comment by pedronauck** [comment]
Babel 6 support now is possible by using [docz-plugin-babel6](https://github.com/pedronauck/docz/tree/master/packages/docz-plugin-babel6) release in [v0.2.6](https://github.com/pedronauck/docz/releases/tag/v0.2.6)

```js
// doczrc.js
import { babel } from 'docz-plugin-babel6'

export default {
  plugins: [babel()]
}
```

**Comment by hariDasu** [comment]
`docz-plugin-babel6` did not solve this problem for me, attempting to use with react native

**Comment by pedronauck** [comment]
`docz-plugin-babel6` was deprecated @hariDasu, we don't support older version of babel at all

**Comment by hariDasu** [comment]
@pedronauck thanks, although making sure im on babel7 and using [this article's libs and version numbers](https://medium.com/doczoficial/https-medium-com-doczoficial-docz-faces-react-native-8efbbf3d73) combinatorially [with those shown here](https://github.com/pedronauck/docz-plugin-react-native/blob/master/example/package.json) seem to result in the same error to no avail. 

IMO, in a small team without a person or team dedicated to maintaining RN component documentation, this is a battle not worth fighting. I've tried storybookJS, docz, styleguidist, and none of them seem to work consistently, due to webpack, babel, RN versions expo versions, etc. etc. perhaps I shall just wait a bit longer for these issues to resolve over time.
