### ISSUE TITLE
TypeError: (filePath || "<unknown>").replace is not a function

### ISSUE THREAD

**Issue by capaj** [pedronauck/docz#344]
## Bug Report

**Describe the bug**

when compiling docz for the first time I get 
```
TypeError: (filePath || "<unknown>").replace is not a function
```

**To Reproduce**

1. `yarn add docz`
2. `npx docz dev`

```shell
 WAIT  Compiling...                                                                                 02:52:10

/home/capaj/git_projects/graphql-repos/typegql/node_modules/webpack-hot-client/lib/index.js:48
      .replace(context, '')
       ^

TypeError: (filePath || "<unknown>").replace is not a function
    at invalid (/home/capaj/git_projects/graphql-repos/typegql/node_modules/webpack-hot-client/lib/index.js:
48:8)
    at comp.hooks.invalid.tap (/home/capaj/git_projects/graphql-repos/typegql/node_modules/webpack-hot-clien
t/lib/index.js:64:7)
    at SyncHook.eval [as call] (eval at create (/home/capaj/git_projects/graphql-repos/typegql/node_modules/
tapable/lib/HookCodeFactory.js:19:10), <anonymous>:9:1)
    at Watchpack.watcher.compiler.watchFileSystem.watch (/home/capaj/git_projects/graphql-repos/typegql/node
_modules/webpack/lib/Watching.js:139:33)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Watchpack.emit (events.js:214:7)
    at Watchpack._onChange (/home/capaj/git_projects/graphql-repos/typegql/node_modules/watchpack/lib/watchp
ack.js:118:7)
    at Watchpack.<anonymous> (/home/capaj/git_projects/graphql-repos/typegql/node_modules/watchpack/lib/watc
hpack.js:109:8)
    at emitTwo (events.js:126:13)
    at Watcher.emit (events.js:214:7)
    at /home/capaj/git_projects/graphql-repos/typegql/node_modules/watchpack/lib/DirectoryWatcher.js:101:9
    at Array.forEach (<anonymous>)
    at DirectoryWatcher.setFileTime (/home/capaj/git_projects/graphql-repos/typegql/node_modules/watchpack/l
ib/DirectoryWatcher.js:99:42)
    at DirectoryWatcher.onFileAdded (/home/capaj/git_projects/graphql-repos/typegql/node_modules/watchpack/l
ib/DirectoryWatcher.js:250:7)
    at emitTwo (events.js:126:13)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Environment**

* OS: [ubuntu
* Node/npm version: Node 8/yarn 1.9.4

**Comment by capaj** [comment]
hmm so it ran fine the second time. Closing.
