### ISSUE TITLE
TypeError: s is not a function when running docz dev

### ISSUE THREAD

**Issue by capaj** [pedronauck/docz#358]
```
TypeError: s is not a function
    at parseHtml (/home/capaj/git_projects/graphql-repos/typegql/node_modules/docz-core/dist/index.js:1:18066)
    at template (/home/capaj/git_projects/graphql-repos/typegql/node_modules/docz-core/dist/index.js:1:20129)
    at MiniHtmlWebpackPlugin.plugin (/home/capaj/git_projects/graphql-repos/typegql/node_modules/mini-html-webpack-plugin/index.js:17:33)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/capaj/git_projects/graphql-repos/typegql/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook (/home/capaj/git_projects/graphql-repos/typegql/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.emitAssets (/home/capaj/git_projects/graphql-repos/typegql/node_modules/webpack/lib/Compiler.js:364:19)
    at onCompiled (/home/capaj/git_projects/graphql-repos/typegql/node_modules/webpack/lib/Compiler.js:231:9)
    at hooks.afterCompile.callAsync.err (/home/capaj/git_projects/graphql-repos/typegql/node_modules/webpack/lib/Compiler.js:553:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/capaj/git_projects/graphql-repos/typegql/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/home/capaj/git_projects/graphql-repos/typegql/node_modules/tapable/lib/Hook.js:154:20)
    at compilation.seal.err (/home/capaj/git_projects/graphql-repos/typegql/node_modules/webpack/lib/Compiler.js:550:30)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/capaj/git_projects/graphql-repos/typegql/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/home/capaj/git_projects/graphql-repos/typegql/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeAssets.callAsync.err (/home/capaj/git_projects/graphql-repos/typegql/node_modules/webpack/lib/Compilation.js:1295:35)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/capaj/git_projects/graphql-repos/typegql/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/home/capaj/git_projects/graphql-repos/typegql/node_modules/tapable/lib/Hook.js:154:20)
```

when I put a `indexHtml` into `doczrc.js`

on 0.11.2

Also the error is only displayed when I send an interrupt. It's just stuck until then. IMHO the error should be thrown as soon as it is encountered.

**Comment by pedronauck** [comment]
Can you give a shot of your `indexHtml`, please?

**Comment by Glazy** [comment]
Any update on this @capaj? 😁

**Comment by capaj** [comment]
@Glazy oh sorry, totally forgot about this. Will try it now on `0.13.7`

**Comment by capaj** [comment]
@Glazy actually this issue appeared once as I tried it. The second time it probably blasted the cache and started to build again. The problem doesn't appear again so I guess this can be closed.
Although I am a bit confused about the indexHtml config. If I put in random string there I would expect the build to fail as docz is not able to find that file, but no. It builds fine, no matter what random string I put there. I'll open up a new issue for that.
