### ISSUE TITLE
Failed to minify the bundle

### ISSUE THREAD

**Issue by byronwilliams** [pedronauck/docz#371]
## Bug Report

**Fresh docz does not build**

*If I create a new docz project and type yarn docz build it fails to minify*

**To Reproduce**

```bash
$ mkdir -p /tmp/testdocz
$ cd /tmp/testdocz
$ yarn add docz
$ yarn docz build
```

```shell
byron@chaol /t/test> yarn docz build
yarn docz v1.0.2
warning package.json: No license field
$ "/tmp/test/node_modules/.bin/docz" "build"
▶  start     Creating an optimized production build...
✖  fatal     Failed to compile.

Failed to minify the bundle. Error: static/js/vendors.cd560ad7.js from UglifyJs
undefined
    at Promise (/tmp/test/node_modules/docz-core/dist/index.js:1:22363)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Read more here: http://bit.ly/2tRViJ9

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Expected behavior**

My docs to be built

**Environment**

```shell
byron@chaol ~/p/f/v2> uname -a
Linux chaol 4.18.9-arch1-1-ARCH #1 SMP PREEMPT Wed Sep 19 21:19:17 UTC 2018 x86_64 GNU/Linux

byron@chaol ~/p/f/v2> node -v
v10.11.0

byron@chaol ~/p/f/v2> npm version
{ npm: '6.4.1',
  ares: '1.14.0',
  cldr: '33.1',
  http_parser: '2.8.1',
  icu: '62.1',
  modules: '64',
  napi: '3',
  nghttp2: '1.33.0',
  node: '10.11.0',
  openssl: '1.1.1',
  tz: '2018e',
  unicode: '11.0',
  uv: '1.23.0',
  v8: '6.8.275.32-node.28',
  zlib: '1.2.11' }

byron@chaol ~/p/f/v2> yarn -v
1.0.2

byron@chaol ~/p/f/v2> cat package.json 
{
  "dependencies": {
    "docz": "^0.11.2"
  },
  "scripts": {
    "docz:dev": "docz dev",
    "docz:build": "docz build"
  }
}
```

**Comment by byronwilliams** [comment]
Fixed by v0.12.3
