### ISSUE TITLE
[docz@0.12.5] Could not create Open in CodeSandbox Error, about svg

### ISSUE THREAD

**Issue by amily4555** [pedronauck/docz#399]
## Bug Report

i use SVG, 

svg relative path is right 

and in doczrc.js remove plugin docz-plugin-svgr

use docz:dev && docz:build show error;

```
Could not create Open in CodeSandbox Error: invalid relative path from  to ../assets/bbs.svg
    at rp2 (/Users/Mizi/git/MasterRT/node_modules/codesandboxer/dist/utils/resolvePath.js:12:17)
    at rp2 (/Users/Mizi/git/MasterRT/node_modules/codesandboxer/dist/utils/resolvePath.js:14:16)
    at resolvePath (/Users/Mizi/git/MasterRT/node_modules/codesandboxer/dist/utils/resolvePath.js:42:13)
    at Object.assign.content.internalImports.map.m (/Users/Mizi/git/MasterRT/node_modules/codesandboxer-fs/src/assembleFiles.js:80:43)
    at Array.map (<anonymous>)
    at Object.assembleFiles (/Users/Mizi/git/MasterRT/node_modules/codesandboxer-fs/src/assembleFiles.js:80:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Could not find dependency version for react
Could not find dependency version for react
Could not find dependency version for react
Could not find dependency version for react
Could not find dependency version for react
Could not find dependency version for react
Could not find dependency version for antd
Could not find dependency version for react
Could not find dependency version for react
Could not find dependency version for antd
Could not find dependency version for react
Could not find dependency version for react
Could not find dependency version for react
Could not find dependency version for react
Could not find dependency version for lodash
Could not find dependency version for react
Could not find dependency version for lodash
Could not find dependency version for lodash
```

but, in webpage, can see SVG component 

#383 
#389 
#341

**Comment by pedronauck** [comment]
Fixed on the new release [v0.12.10](https://github.com/pedronauck/docz/releases/tag/v0.12.10) ✅

**Comment by selrond** [comment]
@pedronauck I still have messages like `Could not find dependency version for components/atoms/Typography` (for all kinds of my custom components) all over the place when I run docz.
Any suggestions?

**Comment by pedronauck** [comment]
Are you using relative imports? If you are, you need to set your alias or resolve modules for webpack

**Comment by selrond** [comment]
@pedronauck I'm using `module-resolver` babel plugin:

```js
module.exports = {
  src: path.resolve('./src/components'),
  // ... 
  modifyBabelRc(babelrc) {
    return {
      ...babelrc,
      plugins: [
        ...babelrc.plugins,
        ['module-resolver', { root: [path.resolve('./src')] }]
      ]
    }
  }
}
```

anything I'm missing?
