### ISSUE TITLE
Not working with pnpm

### ISSUE THREAD

**Issue by vjpr** [pedronauck/docz#44]
## Bug Report

**Describe the bug**

Doesn't work with [pnpm](https://pnpm.js.org/)

**To Reproduce**

```
Install with `pnpm install --shamlessly-flatten`

Start it
```

```shell
Module build failed (from ./node_modules/.registry.npmjs.org/happypack/5.0.0/node_modules/happypack/loader.js):
Error: .test must be a string/Function/RegExp, or an array of those
    at assertConfigApplicableTest (xxx/packages/public/apps-templates/docz/node_modules/.registry.npmjs.org/@babel/core/7.0.0-beta.49/node_modules/@babel/core/lib/config/validation/option-assertions.js:121:11)
    at Object.keys.forEach.key (xxx/packages/public/apps-templates/docz/node_modules/.registry.npmjs.org/@babel/core/7.0.0-beta.49/node_modules/@babel/core/lib/config/validation/options.js:99:20)
    at Array.forEach (<anonymous>)
    at validate (xxx/packages/public/apps-templates/docz/node_modules/.registry.npmjs.org/@babel/core/7.0.0-beta.49/node_modules/@babel/core/lib/config/validation/options.js:69:21)
    at assertOverridesList (xxx/packages/public/apps-templates/docz/node_modules/.registry.npmjs.org/@babel/core/7.0.0-beta.49/node_modules/@babel/core/lib/config/validation/options.js:147:7)
    at Object.keys.forEach.key (xxx/packages/public/apps-templates/docz/node_modules/.registry.npmjs.org/@babel/core/7.0.0-beta.49/node_modules/@babel/core/lib/config/validation/options.js:99:20)
    at Array.forEach (<anonymous>)
    at validate (xxx/packages/public/apps-templates/docz/node_modules/.registry.npmjs.org/@babel/core/7.0.0-beta.49/node_modules/@babel/core/lib/config/validation/options.js:69:21)
    at loadPrivatePartialConfig (xxx/packages/public/apps-templates/docz/node_modules/.registry.npmjs.org/@babel/core/7.0.0-beta.49/node_modules/@babel/core/lib/config/partial.js:38:50)
    at Object.loadPartialConfig (xxx/packages/public/apps-templates/docz/node_modules/.registry.npmjs.org/@babel/core/7.0.0-beta.49/node_modules/@babel/core/lib/config/partial.js:80:18)
    at Object.<anonymous> (xxx/packages/public/apps-templates/docz/node_modules/.registry.npmjs.org/babel-loader/8.0.0-beta.3/990591e7a67c83fd69ae74242914edd8/node_modules/babel-loader/lib/index.js:82:26)
    at Generator.next (<anonymous>)
    at step (xxx/packages/public/apps-templates/docz/node_modules/.registry.npmjs.org/babel-loader/8.0.0-beta.3/990591e7a67c83fd69ae74242914edd8/node_modules/babel-loader/lib/index.js:3:221)
    at _next (xxx/packages/public/apps-templates/docz/node_modules/.registry.npmjs.org/babel-loader/8.0.0-beta.3/990591e7a67c83fd69ae74242914edd8/node_modules/babel-loader/lib/index.js:3:409)
    at xxx/packages/public/apps-templates/docz/node_modules/.registry.npmjs.org/babel-loader/8.0.0-beta.3/990591e7a67c83fd69ae74242914edd8/node_modules/babel-loader/lib/index.js:3:477
    at new Promise (<anonymous>)
```

Also,

```
> @live/app-template-docz@0.1.0 dev xxx/packages/public/apps-templates/docz
> docz dev

ℹ  info      Removing old app files
ℹ  info      Creating new docz files
xxx/packages/public/apps-templates/docz/node_modules/.registry.npmjs.org/happypack/5.0.0/node_modules/happypack/lib/HappyThread.js:175
  throw e;
  ^

Error: spawn /Users/Vaughan/nvm/versions/node/v8.9.0/bin/node EAGAIN
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

*In order to allow us to quickly reproduce you issue please include a link to a reproduction repository.*

**Expected behavior**

*A clear and concise description of what you expected to happen..*

**Enviroment**

* OS: [e.g. OSX 10.13.4, Windows 10] macOS
* Node/npm version: [e.g. Node 8/npm 5] Node 8/pnpm@2.6.1

**Additional context/Screenshots**

**Comment by nicholasess** [comment]
@vjpr the error persist?

**Comment by nicholasess** [comment]
@vjpr I created a project with create-react-app, remove node_modules, install with command: ```pnpm install --shamlessly-flatten```, run ```yarn docz dev``` and it worked.

I need that you create the repository with your packages to reproduce the environment. 

Thanks 👍

**Comment by nicholasess** [comment]
It is image from my repository :) ![captura de tela 2018-09-10 as 20 14 11](https://user-images.githubusercontent.com/3238901/45329314-2c3f2f80-b536-11e8-94a5-bbdf261a4b1f.png)
