### ISSUE TITLE
Not support TypeScript in mdx

### ISSUE THREAD

**Issue by xiaoxiangmoe** [pedronauck/docz#499]
## Bug Report

**Describe the bug**
not support TypeScript in mdx

**To Reproduce**

1. clone docz
2. open typescript example 
3. add deps and run `yarn dev`, it works well
3. see : https://github.com/pedronauck/docz/blob/4b959b9c957b3c7d0eaa05322827fa12b3a79891/examples/babel6/src/components/Alert.mdx#L32-L40
4. change  https://github.com/pedronauck/docz/blob/4b959b9c957b3c7d0eaa05322827fa12b3a79891/examples/babel6/src/components/Alert.mdx#L34 from `const message = 'Hello world'` to `const message:string = 'Hello world'`
5. run `yarn dev`

```shell
 ERROR  Failed to compile with 1 errors                                                                 4:11:18 PM

 error  in ./src/components/Alert.mdx

Module build failed (from ./node_modules/@mdx-js/loader/index.js):
TypeError: (intermediate value).slice is not a function
    at addPropsOnPlayground (/Users/xijinping/playground/ts-docz/node_modules/rehype-docz/dist/index.js:1:733)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)

 @ ./.docz/app/imports.js 14:11-16:31
 @ ./node_modules/docz/dist/index.m.js
 @ ./node_modules/docz-theme-default/dist/index.m.js
 @ ./.docz/app/root.jsx
 @ ./.docz/app/index.jsx
 @ multi ./node_modules/@babel/polyfill/lib/index.js ./.docz/app/index.jsx
```

**Expected behavior**

*A clear and concise description of what you expected to happen..*

**Environment**

* OS: macOS 10.14.1 (18B75)
* node v11.2.0
* yarn v1.12.3

**Comment by xiaoxiangmoe** [comment]
@pedronauck 

see: https://github.com/pedronauck/docz/blob/94b4467113a0ec7457c05d25d7f60d21cf6de39d/examples/typescript/doczrc.js#L1-L4
