### ISSUE TITLE
Module not found: Can't resolve 'null' in '\.docz\app'

### ISSUE THREAD

**Issue by cryzzchen** [pedronauck/docz#550]
## Bug Report

docz@0.12.17
docz-core@0.12.16

Run dev:
```
D:\def\test\manual-test\node_modules\docz\node_modules\docz-core\dist\index.js:1
(function (exports, require, module, __filename, __dirname) { "use strict";function _interopDefault(e){return e&&"object"==typeof e&&"default"in e?e.default:e}Object.defineProperty(exports,"__esModule",{value:!0});var detectPort=_interopDefault(require("detect-port")),equal=_interopDefault(require("fast-deep-equal")),remarkParse=_interopDefault(require("remark-parse")),glob=_interopDefault(require("fast-glob")),fs=require("fs"),fs__default=_interopDefault(fs),resolve=_interopDefault(require("resolve")),artTemplate=require("art-template"),doczUtils=require("docz-utils"),crypto=require("crypto"),slugify=_interopDefault(require("@sindresorhus/slugify")),pReduce=_interopDefault(require("p-reduce")),getPkgRepo=_interopDefault(require("get-pkg-repo")),findup=_interopDefault(require("find-up")),chokidar=_interopDefault(require("chokidar")),WS=_interopDefault(require("ws")),merge=_interopDefault(require("deepmerge")),webpackBarPlugin=_

TypeError: n is not a function
    at parseHtml (D:\def\test\manual-test\node_modules\docz\node_modules\docz-core\dist\index.js:1:101237)
    at template (D:\def\test\manual-test\node_modules\docz\node_modules\docz-core\dist\index.js:1:103575)
    at MiniHtmlWebpackPlugin.plugin (D:\def\test\manual-test\node_modules\mini-html-webpack-plugin\index.js:17:33)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\def\test\manual-test\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:12:1)
    at AsyncSeriesHook.lazyCompileHook (D:\def\test\manual-test\node_modules\tapable\lib\Hook.js:154:20)
    at Compiler.emitAssets (D:\def\test\manual-test\node_modules\webpack\lib\Compiler.js:363:19)
    at onCompiled (D:\def\test\manual-test\node_modules\webpack\lib\Watching.js:50:19)
    at hooks.afterCompile.callAsync.err (D:\def\test\manual-test\node_modules\webpack\lib\Compiler.js:552:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\def\test\manual-test\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (D:\def\test\manual-test\node_modules\tapable\lib\Hook.js:154:20)
    at compilation.seal.err (D:\def\test\manual-test\node_modules\webpack\lib\Compiler.js:549:30)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\def\test\manual-test\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:9:1)
    at AsyncSeriesHook.lazyCompileHook (D:\def\test\manual-test\node_modules\tapable\lib\Hook.js:154:20)
    at hooks.optimizeAssets.callAsync.err (D:\def\test\manual-test\node_modules\webpack\lib\Compilation.js:1323:35)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\def\test\manual-test\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:9:1)
    at AsyncSeriesHook.lazyCompileHook (D:\def\test\manual-test\node_modules\tapable\lib\Hook.js:154:20)
```

Run build:
```
./.docz/app/root.jsx
Module not found: Can't resolve 'null' in 'D:\def\test\manual-test\.docz\app'
```

**Comment by clock157** [comment]
@cryzzchen how to resolved?

**Comment by cryzzchen** [comment]
@clock157 I use npm-shrinkwrap to lock dependency.https://stackoverflow.com/questions/44258235/what-is-the-difference-between-npm-shrinkwrap-json-and-package-lock-json

**Comment by tclain** [comment]
could you elaborate ? We got the same issue her.
