### ISSUE TITLE
TypeError: n is not a function

### ISSUE THREAD

**Issue by HanyRabah** [pedronauck/docz#552]
## Bug Report

*Something broken when webpack trying to compile with docz-core.*

**To Reproduce**
> Yarn docz dev

```shell
yarn run v1.12.3
$ docz dev 
✓ Creating app... 1 ms
✓ Parsing mdx files 74 ms
Happy[jsx]: Version: 5.0.0. Threads: 6 (shared pool)
➤ ｢wds｣: SockJS v0.3.19 bound to "/sockjs-node"
✓ Starting your server 1 ms
⠹ Initializing data server  77%                 234ms, estimated 303ms
Happy[jsx]: All set; signaling webpack to proceed.
✓ Initializing data server 273 ms
Happy[mdx]: All set; signaling webpack to proceed.
/Users/rabah/Projects/dbz-ui-framework/node_modules/docz/node_modules/docz-core/dist/index.js:1
(function (exports, require, module, __filename, __dirname) { "use strict";function _interopDefault(e){return e&&"object"==typeof e&&"default"in e?e.default:e}Object.defineProperty(exports,"__esModule",{value:!0});var detectPort=_interopDefault(require("detect-port")),equal=_interopDefault(require("fast-deep-equal")),remarkParse=_interopDefault(require("remark-parse")),glob=_interopDefault(require("fast-glob")),resolve=_interopDefault(require("resolve")),artTemplate=require("art-template"),doczUtils=require("docz-utils"),crypto=require("crypto"),slugify=_interopDefault(require("@sindresorhus/slugify")),pReduce=_interopDefault(require("p-reduce")),getPkgRepo=_interopDefault(require("get-pkg-repo")),findup=_interopDefault(require("find-up")),chokidar=_interopDefault(require("chokidar")),WS=_interopDefault(require("ws")),merge=_interopDefault(require("deepmerge")),getCacheIdentifier=_interopDefault(require("react-de

TypeError: n is not a function
    at parseHtml (/Users/rabah/Projects/dbz-ui-framework/node_modules/docz/node_modules/docz-core/dist/index.js:1:117684)
    at template (/Users/rabah/Projects/dbz-ui-framework/node_modules/docz/node_modules/docz-core/dist/index.js:1:119140)
    at MiniHtmlWebpackPlugin.plugin (/Users/rabah/Projects/dbz-ui-framework/node_modules/mini-html-webpack-plugin/index.js:17:33)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/rabah/Projects/dbz-ui-framework/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/rabah/Projects/dbz-ui-framework/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.emitAssets (/Users/rabah/Projects/dbz-ui-framework/node_modules/webpack/lib/Compiler.js:363:19)
    at onCompiled (/Users/rabah/Projects/dbz-ui-framework/node_modules/webpack/lib/Watching.js:50:19)
    at hooks.afterCompile.callAsync.err (/Users/rabah/Projects/dbz-ui-framework/node_modules/webpack/lib/Compiler.js:552:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/rabah/Projects/dbz-ui-framework/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/rabah/Projects/dbz-ui-framework/node_modules/tapable/lib/Hook.js:154:20)
    at compilation.seal.err (/Users/rabah/Projects/dbz-ui-framework/node_modules/webpack/lib/Compiler.js:549:30)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/rabah/Projects/dbz-ui-framework/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/rabah/Projects/dbz-ui-framework/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeAssets.callAsync.err (/Users/rabah/Projects/dbz-ui-framework/node_modules/webpack/lib/Compilation.js:1323:35)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/rabah/Projects/dbz-ui-framework/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/rabah/Projects/dbz-ui-framework/node_modules/tapable/lib/Hook.js:154:20)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

* OS:  OSX 10.13.6

* Node/npm version: 
Node 11.2.0 
Npm 6.4.1 

Any Idea what is the problem ?
<img width="1916" alt="screen shot 2018-12-24 at 5 08 17 pm" src="https://user-images.githubusercontent.com/1196069/50400230-8a6ae800-079e-11e9-8357-48ac892e63ce.png">

**Comment by HanyRabah** [comment]
Fixed by adding to doczrc.js

```
wrapper: null,
indexHtml: './index.html',
```
