### ISSUE TITLE
Error in docz dev

### ISSUE THREAD

**Issue by ameerthehacker** [pedronauck/docz#553]
When I run docz dev i get the following error

```sh
/Users/ameerthehacker/Documents/Sites/React/colossus/node_modules/docz-core/dist/index.js:1
(function (exports, require, module, __filename, __dirname) { "use strict";function _interopDefault(e){return e&&"object"==typeof e&&"default"in e?e.default:e}Object.defineProperty(exports,"__esModule",{value:!0});var detectPort=_interopDefault(require("detect-port")),equal=_interopDefault(require("fast-deep-equal")),remarkParse=_interopDefault(require("remark-parse")),glob=_interopDefault(require("fast-glob")),resolve=_interopDefault(require("resolve")),artTemplate=require("art-template"),doczUtils=require("docz-utils"),crypto=require("crypto"),slugify=_interopDefault(require("@sindresorhus/slugify")),pReduce=_interopDefault(require("p-reduce")),getPkgRepo=_interopDefault(require("get-pkg-repo")),findup=_interopDefault(require("find-up")),chokidar=_interopDefault(require("chokidar")),WS=_interopDefault(require("ws")),merge=_interopDefault(require("deepmerge")),getCacheIdentifier=_interopDefault(require("react-dev-ut

TypeError: n is not a function
    at parseHtml (/Users/ameerthehacker/Documents/Sites/React/colossus/node_modules/docz-core/dist/index.js:1:117684)
    at template (/Users/ameerthehacker/Documents/Sites/React/colossus/node_modules/docz-core/dist/index.js:1:119140)
    at MiniHtmlWebpackPlugin.plugin (/Users/ameerthehacker/Documents/Sites/React/colossus/node_modules/mini-html-webpack-plugin/index.js:17:33)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/ameerthehacker/Documents/Sites/React/colossus/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/ameerthehacker/Documents/Sites/React/colossus/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.emitAssets (/Users/ameerthehacker/Documents/Sites/React/colossus/node_modules/docz-core/node_modules/webpack/lib/Compiler.js:363:19)
    at onCompiled (/Users/ameerthehacker/Documents/Sites/React/colossus/node_modules/docz-core/node_modules/webpack/lib/Watching.js:50:19)
    at hooks.afterCompile.callAsync.err (/Users/ameerthehacker/Documents/Sites/React/colossus/node_modules/docz-core/node_modules/webpack/lib/Compiler.js:552:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/ameerthehacker/Documents/Sites/React/colossus/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/ameerthehacker/Documents/Sites/React/colossus/node_modules/tapable/lib/Hook.js:154:20)
    at compilation.seal.err (/Users/ameerthehacker/Documents/Sites/React/colossus/node_modules/docz-core/node_modules/webpack/lib/Compiler.js:549:30)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/ameerthehacker/Documents/Sites/React/colossus/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:9:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/ameerthehacker/Documents/Sites/React/colossus/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeAssets.callAsync.err (/Users/ameerthehacker/Documents/Sites/React/colossus/node_modules/docz-core/node_modules/webpack/lib/Compilation.js:1323:35)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/ameerthehacker/Documents/Sites/React/colossus/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:9:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/ameerthehacker/Documents/Sites/React/colossus/node_modules/tapable/lib/Hook.js:154:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-boilerplate@1.0.0 docz:dev: `docz dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-boilerplate@1.0.0 docz:dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ameerthehacker/.npm/_logs/2018-12-26T14_05_54_040Z-debug.log
```

**Comment by ameerthehacker** [comment]
My package.json file is 

```json
{
  "name": "react-boilerplate",
  "version": "1.0.0",
  "description": "A react scaffold with react, typescript, jest, prettier, tslint, scss, husky",
  "scripts": {
    "start": "cross-env NODE_ENV=development webpack-dev-server --config build/webpack.config.js --open --progress",
    "test": "jest",
    "build": "cross-env NODE_ENV=development webpack --config build/webpack.config.js --progress",
    "build:watch": "cross-env NODE_ENV=development webpack --config build/webpack.config.js --progress --watch",
    "build:prod": "cross-env NODE_ENV=production webpack --config build/webpack.config.js --progress",
    "coverage": "jest --coverage",
    "lint": "tslint **/**.ts? --fix",
    "pretty": "prettier --write",
    "precommit": "lint-staged",
    "prepush": "npm run test",
    "docz:dev": "docz dev"
  },
  "lint-staged": {
    "*.{ts,tsx}": [
      "npm test",
      "npm run pretty",
      "npm run lint",
      "git add"
    ],
    "*.{scss,json,md,js,jsx}": [
      "npm run pretty",
      "git add"
    ]
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/ameerthehacker/react-boilerplate.git"
  },
  "keywords": [
    "react",
    "webpack",
    "typescript",
    "boilerplate"
  ],
  "author": "ameerthehacker",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/ameerthehacker/react-boilerplate/issues"
  },
  "homepage": "https://github.com/ameerthehacker/react-boilerplate#readme",
  "devDependencies": {
    "@babel/core": "^7.2.2",
    "@babel/preset-react": "^7.0.0",
    "@types/enzyme": "^3.1.14",
    "@types/enzyme-adapter-react-16": "^1.0.3",
    "@types/jest": "^23.3.2",
    "@types/react": "^16.4.14",
    "@types/react-dom": "^16.0.7",
    "autoprefixer": "^9.1.5",
    "babel-loader": "^8.0.4",
    "cross-env": "^5.2.0",
    "css-loader": "^1.0.0",
    "docz": "^0.13.5",
    "docz-core": "^0.13.5",
    "enzyme": "^3.6.0",
    "enzyme-adapter-react-16": "^1.5.0",
    "enzyme-to-json": "^3.3.4",
    "file-loader": "^2.0.0",
    "html-webpack-plugin": "^3.2.0",
    "husky": "^0.14.3",
    "jest": "^23.6.0",
    "lint-staged": "^7.2.2",
    "mini-css-extract-plugin": "^0.4.3",
    "node-sass": "^4.9.3",
    "optimize-css-assets-webpack-plugin": "^5.0.1",
    "postcss-loader": "^3.0.0",
    "precss": "^3.1.2",
    "prettier": "^1.14.3",
    "sass-loader": "^7.1.0",
    "style-loader": "^0.23.0",
    "ts-jest": "^23.10.0",
    "ts-loader": "^5.1.1",
    "tslint": "^5.11.0",
    "tslint-react": "^3.6.0",
    "typescript": "^3.0.3",
    "uglifyjs-webpack-plugin": "^2.0.1",
    "url-loader": "^1.1.1",
    "webpack": "^4.19.1",
    "webpack-cli": "^3.1.0",
    "webpack-dev-server": "^3.1.8",
    "webpack-merge": "^4.1.4"
  },
  "dependencies": {
    "react": "^16.5.2",
    "react-dom": "^16.5.2"
  }
}
```

**Comment by matextrem** [comment]
Duplicate #552

**Comment by ameerthehacker** [comment]
Thanks @matextrem just now checked it out!
