### ISSUE TITLE
Docz requires a Webpack install

### ISSUE THREAD

**Issue by oliverjam** [pedronauck/docz#56]
## Bug Report

We didn't have Webpack installed, so Docz threw an error when running `docz dev`:

```shell
Error: Cannot find module 'webpack/schemas/WebpackOptions.json'
```

`npm i -D webpack` fixed the error immediately.

**To Reproduce**

1. Create a project without Webpack installed
2. Install Docz `npm i -D docz`
3. Run `npx docz dev`

```shell
❯ npm run docz:dev

> test@ docz:dev /Users/oliver.phillips/Code/mosaic-project/mosaic
> docz dev

module.js:549
    throw err;
    ^

Error: Cannot find module 'webpack/schemas/WebpackOptions.json'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/oliver.phillips/Code/mosaic-project/mosaic/node_modules/@webpack-contrib/config-loader/lib/index.js:4:23)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/oliver.phillips/Code/mosaic-project/mosaic/node_modules/webpack-serve/lib/config.js:3:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
npm ERR! code ELIFECYCLE
```

**Expected behavior**

Docz should either have Webpack as a dependency or at least warn that a peerDependency is missing.

**Environment**

* OS: macOS 10.13.5
* Node/npm version: Node v8.11.1/npm v6.0.1

**Comment by pedronauck** [comment]
Sorry, but I started a new folder here with just docz as dependency, then ran: `npx docz dev` e didn't happen any error. Can you give some information about your project?

**Comment by oliverjam** [comment]
Hmm you're right, I just tried that and it worked fine. We were also using Babel 6 so it's possible that was the real underlying cause, sorry!

**Comment by chrstntdd** [comment]
Encountering this exact same issue. Re-cloned my project, installed fresh dependencies, and then installed `docz` with `npm i -D docz`. Running `docz dev` caused the same error message as the OP 😢

Project is already running on `webpack 2.6.1`.

**Comment by pedronauck** [comment]
So, you need webpack 4 to run docz, if you use webpack 2.6.1 you won't be abble to run @chrstntdd

**Comment by chrstntdd** [comment]
@pedronauck Ahh. Welp, time to hit that big upgrade button. Thank you!
