### ISSUE TITLE
Can't execute docz in Laravel project

### ISSUE THREAD

**Issue by Epistol** [pedronauck/docz#58]
## Bug Report

**Describe the bug**

Hi, when I try to install docz, everything's fine but when I try to launch it, i got this error : 

```shell
C:\xampp\htdocs\cdg_reload>yarn docz dev
yarn run v1.7.0
$ C:\xampp\htdocs\cdg_reload\node_modules\.bin\docz dev
i  info      Removing old app files
i  info      Creating new docz files
i  info      Setup entries socket on port 8089

Compiling

* Client █████████████████████████ building modules (29%) 161/167 modules 6 active
  node_modules\core-js\modules\_string-ws.js

C:\xampp\htdocs\cdg_reload\node_modules\snapdragon\lib\parser.js:473
        throw new Error('no parsers registered for: "' + self.input.slice(0, 5) + '"');
        ^

Error: no parsers registered for: "]a(r)"
    at parse (C:\xampp\htdocs\cdg_reload\node_modules\snapdragon\lib\parser.js:473:15)
    at Parser.parse (C:\xampp\htdocs\cdg_reload\node_modules\snapdragon\lib\parser.js:477:24)
    at Snapdragon.parse (C:\xampp\htdocs\cdg_reload\node_modules\snapdragon\index.js:122:28)
    at Snapdragon.<anonymous> (C:\xampp\htdocs\cdg_reload\node_modules\braces\lib\braces.js:40:45)
    at Braces.parse (C:\xampp\htdocs\cdg_reload\node_modules\braces\lib\braces.js:66:26)
    at Braces.expand (C:\xampp\htdocs\cdg_reload\node_modules\braces\lib\braces.js:87:18)
    at create (C:\xampp\htdocs\cdg_reload\node_modules\braces\index.js:142:15)
    at memoize (C:\xampp\htdocs\cdg_reload\node_modules\braces\index.js:298:13)
    at Function.braces.create (C:\xampp\htdocs\cdg_reload\node_modules\braces\index.js:165:10)
    at Function.braces.expand (C:\xampp\htdocs\cdg_reload\node_modules\braces\index.js:81:17)
    at getDirParts (C:\xampp\htdocs\cdg_reload\node_modules\chokidar\index.js:435:31)
    at FSWatcher.<anonymous> (C:\xampp\htdocs\cdg_reload\node_modules\chokidar\index.js:452:24)
    at C:\xampp\htdocs\cdg_reload\node_modules\readdirp\readdirp.js:226:72
    at Array.filter (<anonymous>)
    at C:\xampp\htdocs\cdg_reload\node_modules\readdirp\readdirp.js:226:12
    at C:\xampp\htdocs\cdg_reload\node_modules\readdirp\readdirp.js:199:38
error Command failed with exit code 1.


```

**To Reproduce**

1. Create a Laravel 5.6 project
2. Add some scss content, update, etc all this stuff
3. Install docz
4. Launch docz 
5. See error

**Enviroment**

* OS: Windows 10 
* Node/npm version: Node v8.9.2 & npm : v5.8.0

Thank's :)

**Comment by ahmedelgabri** [comment]
Same is happening with me:

**Enviroment**

- OS: macOS High Sierra 10.13.5
- Node/npm/yarn version: Node v8.9.1 & npm : v5.5.1 & yarn 1.7.0 (I use yarn in this project)

**Comment by nicholasess** [comment]
@Epistol can you update version of docz, remove path .docz and run docz dev? If happened the same error, tell me please.

**Comment by nicholasess** [comment]
@ahmedelgabri can you test the same procedure that I said to @Epistol?

**Comment by pedronauck** [comment]
Closed due to no response!

**Comment by aheidelberg** [comment]
I'm getting the exact same error as @Epistol even after removing `.docz` and running `docz dev` again ([composer.json](https://gist.github.com/aheidelberg/11d9802dea04726cf2d88d5259871d14)).

**Comment by camflan** [comment]
To get around this, I set the `src` config to be a subdirectory where my js src files are located, not the project root

**Comment by jeankvd** [comment]
@camflan how'd you do that?

**Comment by camflan** [comment]
https://www.docz.site/documentation/project-configuration

Config file with `src` set to the root path where your is files are
