### ISSUE TITLE
Error: Cannot find module './lib/_stream_writable.js'

### ISSUE THREAD

**Issue by clock157** [pedronauck/docz#589]
## Bug Report

**Describe the bug**
update dependencies, run `docz dev`, show these error, the dev server can be start up, but lost my configure in doczrc.js.

**To Reproduce**
docz dev

```shell
{ /Users/puwei/Code/gitlab.alipay-inc.com/LinkE/linke-fc/node_modules/_load-cfg@0.11.1@load-cfg/node_modules/esm/esm.js:1
Error: Cannot find module './lib/_stream_writable.js'
    at new <anonymous> (/Users/puwei/Code/gitlab.alipay-inc.com/LinkE/linke-fc/node_modules/_load-cfg@0.11.1@load-cfg/node_modules/esm/esm.js:1)
    at Proxy.<anonymous> (/Users/puwei/Code/gitlab.alipay-inc.com/LinkE/linke-fc/node_modules/_load-cfg@0.11.1@load-cfg/node_modules/esm/esm.js:1)
    at Proxy.<anonymous> (/Users/puwei/Code/gitlab.alipay-inc.com/LinkE/linke-fc/node_modules/_load-cfg@0.11.1@load-cfg/node_modules/esm/esm.js:1)
    at Object.<anonymous> (/Users/puwei/Code/gitlab.alipay-inc.com/LinkE/linke-fc/node_modules/_load-cfg@0.11.1@load-cfg/node_modules/esm/esm.js:1)
    at Object.t (/Users/puwei/Code/gitlab.alipay-inc.com/LinkE/linke-fc/node_modules/_load-cfg@0.11.1@load-cfg/node_modules/esm/esm.js:1)
    at l (/Users/puwei/Code/gitlab.alipay-inc.com/LinkE/linke-fc/node_modules/_load-cfg@0.11.1@load-cfg/node_modules/esm/esm.js:1)
    at Object.<anonymous> (/Users/puwei/Code/gitlab.alipay-inc.com/LinkE/linke-fc/node_modules/_duplexify@3.6.1@duplexify/node_modules/readable-stream/readable.js:15:22)
    at Object.<anonymous> (/Users/puwei/Code/gitlab.alipay-inc.com/LinkE/linke-fc/node_modules/_load-cfg@0.11.1@load-cfg/node_modules/esm/esm.js:1)
    at /Users/puwei/Code/gitlab.alipay-inc.com/LinkE/linke-fc/node_modules/_load-cfg@0.11.1@load-cfg/node_modules/esm/esm.js:1
    at Generator.next (<anonymous>)
    at Zl (/Users/puwei/Code/gitlab.alipay-inc.com/LinkE/linke-fc/node_modules/_load-cfg@0.11.1@load-cfg/node_modules/esm/esm.js:1)
    at ou (/Users/puwei/Code/gitlab.alipay-inc.com/LinkE/linke-fc/node_modules/_load-cfg@0.11.1@load-cfg/node_modules/esm/esm.js:1)
    at Object.f (/Users/puwei/Code/gitlab.alipay-inc.com/LinkE/linke-fc/node_modules/_load-cfg@0.11.1@load-cfg/node_modules/esm/esm.js:1)
    at Object.o._compile (/Users/puwei/Code/gitlab.alipay-inc.com/LinkE/linke-fc/node_modules/_load-cfg@0.11.1@load-cfg/node_modules/esm/esm.js:1)
    at Object.Module._extensions..js (module.js:664:10)
    at Object.Zp (/Users/puwei/Code/gitlab.alipay-inc.com/LinkE/linke-fc/node_modules/_load-cfg@0.11.1@load-cfg/node_modules/esm/esm.js:1)
    at Object.p (/Users/puwei/Code/gitlab.alipay-inc.com/LinkE/linke-fc/node_modules/_load-cfg@0.11.1@load-cfg/node_modules/esm/esm.js:1)
    at Object.<anonymous> (/Users/puwei/Code/gitlab.alipay-inc.com/LinkE/linke-fc/node_modules/_load-cfg@0.11.1@load-cfg/node_modules/esm/esm.js:1
● Client █████████████████████████ building (13%) 31/41 modules 10 active  node_modules/_chalk@2.4.2@chalk/templates.js
✓ Initializing data server 482 ms
```

**Expected behavior**
work.

**Environment**

* OS: OSX 10.14.2
* Node/npm version: v8.11.1 / 5.6.0

**Additional context/Screenshots**

**Comment by clock157** [comment]
looks like the esm packages has some break change three days ago?https://www.npmjs.com/package/esm
