### ISSUE TITLE
Adding babel-plugin-react-docgen makes the build fail

### ISSUE THREAD

**Issue by fzaninotto** [pedronauck/docz#72]
## Bug Report

When running the `yarn dev` command, docz fails with:

```
ERROR  Failed to compile with 1 errors                                                                                                             23:12:28

 error  in ./root/src/button/EditButton.mdx

Module build failed (from ./node_modules/happypack/loader.js):
TypeError: /path/to/root/src/button/EditButton.mdx: Cannot read property '0' of null
    at Buffer._append (/path/to/node_modules/babel-generator/lib/buffer.js:95:25)
    at Buffer.append (/path/to/node_modules/babel-generator/lib/buffer.js:72:10)
    at Generator._append (/path/to/node_modules/babel-generator/lib/printer.js:206:52)
    at Generator.word (/path/to/node_modules/babel-generator/lib/printer.js:131:10)
    at Generator.Identifier (/path/to/node_modules/babel-generator/lib/generators/types.js:38:8)
    at /path/to/node_modules/babel-generator/lib/printer.js:298:23
    at Buffer.withSource (/path/to/node_modules/babel-generator/lib/buffer.js:168:5)
    at Generator.withSource (/path/to/node_modules/babel-generator/lib/printer.js:189:15)
    at Generator.print (/path/to/node_modules/babel-generator/lib/printer.js:297:10)
    at Generator.MemberExpression (/path/to/node_modules/babel-generator/lib/generators/expressions.js:216:8)
    at /path/to/node_modules/babel-generator/lib/printer.js:298:23
    at Buffer.withSource (/path/to/node_modules/babel-generator/lib/buffer.js:168:5)
    at Generator.withSource (/path/to/node_modules/babel-generator/lib/printer.js:189:15)
    at Generator.print (/path/to/node_modules/babel-generator/lib/printer.js:297:10)
    at Generator.AssignmentExpression (/path/to/node_modules/babel-generator/lib/generators/expressions.js:190:8)
    at /path/to/node_modules/babel-generator/lib/printer.js:298:23

 @ ./.docz/app/imports.js 8:11-170
 @ ./.docz/app/index.jsx
 @ multi ./node_modules/docz-core/node_modules/babel-polyfill/lib/index.js ./.docz/app/index.jsx
```

It started failing after I added `babel-plugin-react-docgen`, which seems to be necessary for the `<PropsTable>` component to work:

```
yarn add -W babel-plugin-react-docgen --dev
```

This installed babel-plugin-react-docgen v2.0.0-rc.1

I add the plugin to my `.babelrc`, call `yarn dev`, and the build fails. If I remove the plugin from `.babelrc`, run `yarn dev`, it works smoothly.

My mdx has nothing special:

```mdx
---
name: EditButton
---

import { Playground } from 'docz';

## Basic Usage

<Playground>
<div></div>
</Playground>
```

**Environment**

* OS: OSX
* Using Babel6 plugin
* Node 9.8.0/yarn 1.6.0

**Comment by pedronauck** [comment]
If you see at the `babel6` example folder, we're just using the plugin in the `doczrc.js` and the project are running like expected as others examples!

**Comment by fzaninotto** [comment]
You're right, my mistake.

I tried adding the plugin because `<PropsTable>` didn't output anything, and I couldn't find the dependency in your package.json. So I thought I was missing an installation step.

But it turns out I was trying to document a component decorated by a HOC, which has no props.  Trying with a regular component shows the props table all right.

Sorry for the false alarm, keep up the good work!

**Comment by pedronauck** [comment]
Great, any doubt please contact us ✌️
