### ISSUE TITLE
[v1.0.0-rc8] Typescript components with multiple exports crash server/build

### ISSUE THREAD

**Issue by msokk** [pedronauck/docz#769]
## Bug Report

When trying to write props cache, the docgen parser fails with files having multiple exports.

I traced the failure to this line:
https://github.com/pedronauck/docz/blob/v1.0.0-rc.8/core/docz-core/src/utils/docgen/typescript.ts#L182

It tries to match props to files by index, but there are more props than files, so there will be records with undefined key.

```shell
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.normalize (path.js:1117:5)
    at items.reduce (./project/node_modules/docz-core/dist/index.js:1509:33)
    at Array.reduce (<anonymous>)
    at writePropsOnCache (./project/node_modules/docz-core/dist/index.js:1508:28)
    at tsParser (./project/node_modules/docz-core/dist/index.js:1639:5)
    at docgen (./project/node_modules/docz-core/dist/index.js:1646:11)
```

**Comment by lesha1201** [comment]
I've made pull request about this

**Comment by pedronauck** [comment]
Fixed, will be released in the next version.
