### ISSUE TITLE
Failed to import and configure babelrc alias through custom plugin

### ISSUE THREAD

**Issue by vpsouza** [pedronauck/docz#82]
## Question
Getting errors trying to configure babelrc aliases.

**Description**
I'm trying to incorporate docz onto my current react app and trying to make docz understand all babel aliases that we used a lot I'm getting an error:

*Give more information about your doubt*

```javascript
// doczrc.js
import {
  createPlugin
} from 'docz-core'

import { css } from 'docz-plugin-css'

const moduleLoader = () => createPlugin({
  modifyBabelRc: (babelrc) => {

    let newBabelrc = Object.assign({}, babelrc);

    newBabelrc.presets.push(["@babel/preset-env", {
      "targets": {
        "browsers": ["last 2 versions"]
      }
    }],
    ["@babel/preset-stage-0", { "decoratorsLegacy": true }]);
    
    newBabelrc.plugins.push(["import", {
      "libraryName": "antd",
      "style": "css"
    }]);

    newBabelrc.plugins.push(
      "@babel/plugin-proposal-class-properties",
      "@babel/plugin-proposal-optional-chaining",
      "@babel/plugin-proposal-pipeline-operator"
    )

    newBabelrc.plugins.push(["module-resolver", {
      "root": ["./client/src"],
      "alias": {
        "mycomponents": "./client/node_modules/admin-components/src",
        "my2app": "./client/src/app"
      }
    }]);

    newBabelrc.plugins.push(["@babel/plugin-transform-runtime", {
      "helpers": false,
      "polyfill": false,
      "regenerator": true
    }]);

    newBabelrc.plugins.push(["react-css-modules", {
      "context": "./client/src",
      "generateScopedName": "[local]-[hash:base64:5]",
      "filetypes": {
        ".scss": {
          "syntax": "postcss-scss"
        }
      },
      "webpackHotModuleReloading": true
    }]);

    return babelrc;
  }
})

export default {
  title: 'Web Admin',
  description: 'Netshoes Web Admin',
  theme: 'docz-theme-default',
  themeConfig: {
    colors: {
      primary: 'tomato',
    },
  },
  port: 3002,
  plugins: [
    css({
      preprocessor: 'postcss',
      cssmodules: true
    }),
    moduleLoader()
  ]
}
```

```shell
yarn run v1.3.2
$ docz dev
ℹ  info      Removing old app files
ℹ  info      Creating new docz files
ℹ  info      Setup entries socket on port 8094
 ERROR  Failed to compile with 1 errors                                                                               20:12:20

 error  in ./.docz/app/index.jsx
Module build failed (from ./node_modules/happypack/loader.js):
Error: [BABEL] /Users/ac-vpiedade/workspaces/netshoes/ff-web-admin/.docz/app/index.jsx: You gave us a visitor for the node type PrivateName but it's not a valid type (While processing: "/Users/ac-vpiedade/workspaces/netshoes/ff-web-admin/node_modules/@
babel/preset-stage-0/lib/index.js$0$0$0$3")    at verify (/Users/ac-vpiedade/workspaces/netshoes/ff-web-admin/node_modules/@babel/traverse/lib/visitors.js:143:13)
    at explode (/Users/ac-vpiedade/workspaces/netshoes/ff-web-admin/node_modules/@babel/traverse/lib/visitors.js:46:3)
    at Object.merge (/Users/ac-vpiedade/workspaces/netshoes/ff-web-admin/node_modules/@babel/traverse/lib/visitors.js:195:5)
    at _default (/Users/ac-vpiedade/workspaces/netshoes/ff-web-admin/node_modules/@babel/preset-stage-3/node_modules/@babel/pl
ugin-proposal-class-properties/lib/index.js:163:61)
    at /Users/ac-vpiedade/workspaces/netshoes/ff-web-admin/node_modules/@babel/preset-stage-3/node_modules/@babel/helper-plugi
n-utils/lib/index.js:19:12
    at loadDescriptor (/Users/ac-vpiedade/workspaces/netshoes/ff-web-admin/node_modules/docz-core/node_modules/@babel/core/lib
/config/full.js:157:14)
    at cachedFunction (/Users/ac-vpiedade/workspaces/netshoes/ff-web-admin/node_modules/docz-core/node_modules/@babel/core/lib/config/caching.js:32:19)
    at loadPluginDescriptor (/Users/ac-vpiedade/workspaces/netshoes/ff-web-admin/node_modules/docz-core/node_modules/@babel/core/lib/config/full.js:192:28)
    at config.plugins.map.descriptor (/Users/ac-vpiedade/workspaces/netshoes/ff-web-admin/node_modules/docz-core/node_modules/@babel/core/lib/config/full.js:68:16)
    at Array.map (<anonymous>)

 @ multi ./node_modules/babel-polyfill/lib/index.js ./.docz/app/index.jsx



 WAIT  Compiling...                                                                                                   20:12:20



 ERROR  Failed to compile with 1 errors                                                                               20:12:22

 error  in ./.docz/app/index.jsx

Module build failed (from ./node_modules/happypack/loader.js):
Error: [BABEL] /Users/ac-vpiedade/workspaces/netshoes/ff-web-admin/.docz/app/index.jsx: You gave us a visitor for the node typ
e PrivateName but it's not a valid type (While processing: "/Users/ac-vpiedade/workspaces/netshoes/ff-web-admin/node_modules/@
babel/preset-stage-0/lib/index.js$0$0$0$3")
    at verify (/Users/ac-vpiedade/workspaces/netshoes/ff-web-admin/node_modules/@babel/traverse/lib/visitors.js:143:13)
    at explode (/Users/ac-vpiedade/workspaces/netshoes/ff-web-admin/node_modules/@babel/traverse/lib/visitors.js:46:3)
    at Object.merge (/Users/ac-vpiedade/workspaces/netshoes/ff-web-admin/node_modules/@babel/traverse/lib/visitors.js:195:5)
    at _default (/Users/ac-vpiedade/workspaces/netshoes/ff-web-admin/node_modules/@babel/preset-stage-3/node_modules/@babel/pl
ugin-proposal-class-properties/lib/index.js:163:61)
    at /Users/ac-vpiedade/workspaces/netshoes/ff-web-admin/node_modules/@babel/preset-stage-3/node_modules/@babel/helper-plugi
n-utils/lib/index.js:19:12
    at loadDescriptor (/Users/ac-vpiedade/workspaces/netshoes/ff-web-admin/node_modules/docz-core/node_modules/@babel/core/lib
/config/full.js:157:14)
    at cachedFunction (/Users/ac-vpiedade/workspaces/netshoes/ff-web-admin/node_modules/docz-core/node_modules/@babel/core/lib/config/caching.js:32:19)
    at loadPluginDescriptor (/Users/ac-vpiedade/workspaces/netshoes/ff-web-admin/node_modules/docz-core/node_modules/@babel/core/lib/config/full.js:192:28)
    at config.plugins.map.descriptor (/Users/ac-vpiedade/workspaces/netshoes/ff-web-admin/node_modules/docz-core/node_modules/@babel/core/lib/config/full.js:68:16)
    at Array.map (<anonymous>)
    at recurseDescriptors (/Users/ac-vpiedade/workspaces/netshoes/ff-web-admin/node_modules/docz-core/node_modules/@babel/core/lib/config/full.js:67:38)
    at recurseDescriptors (/Users/ac-vpiedade/workspaces/netshoes/ff-web-admin/node_modules/docz-core/node_modules/@babel/core/lib/config/full.js:86:27)
    at recurseDescriptors (/Users/ac-vpiedade/workspaces/netshoes/ff-web-admin/node_modules/docz-core/node_modules/@babel/core/lib/config/full.js:86:27)
    at recurseDescriptors (/Users/ac-vpiedade/workspaces/netshoes/ff-web-admin/node_modules/docz-core/node_modules/@babel/core/lib/config/full.js:86:27)
    at recurseDescriptors (/Users/ac-vpiedade/workspaces/netshoes/ff-web-admin/node_modules/docz-core/node_modules/@babel/core/lib/config/full.js:86:27)
    at loadFullConfig (/Users/ac-vpiedade/workspaces/netshoes/ff-web-admin/node_modules/docz-core/node_modules/@babel/core/lib/config/full.js:100:6)

 @ multi ./node_modules/babel-polyfill/lib/index.js ./.docz/app/index.jsx
```

* Twitter: If it's just a quick question you can ping me on Twitter: https://twitter.com/pedronauck

**Comment by pedronauck** [comment]
Hey @vpsouza, Can you give a copy of your `package.json`?

**Comment by vpsouza** [comment]
@pedronauck here the package.json

```javascript
{
  "name": "web-admin",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "docz-dev": "docz dev",
    "docz-build": "docz build",
    "server": "cd client/node_modules/admin-core/server && node --inspect index.js",
    "start": "yarn download && concurrently --kill-others \"yarn server\" \"cd client && PORT=3001 yarn start\"",
    "client": "cd client && yarn start",
    "build": "rm -rf dist && mkdir -p dist/public && cd client && yarn build && cd .. && cp -R client/build/* dist/public && cp -R client/public/* dist/public && cp -R client/node_modules/admin-core/server/* dist && cp -R node_modules dist/node_modules",
    "build:analyzer": "cd client && yarn build:analyzer",
    "test": "cd client && yarn test",
    "test:watch": "cd client && yarn test:watch",
    "lint": "cd client && yarn lint",
    "lint:watch": "cd client && yarn lint:watch",
    "storybook": "cd client && yarn storybook",
    "build-storybook": "cd client && yarn build-storybook",
    "download": "yarn && cd client && yarn && cd .."
  },
  "dependencies": {
    "compression": "^1.6.2",
    "concurrently": "^3.3.0",
    "cookie-parser": "~1.4.3",
    "cors": "^2.8.1",
    "debug": "~2.6.0",
    "express": "~4.14.1",
    "http-proxy-middleware": "^0.17.4",
    "jsonwebtoken": "^7.3.0",
    "knox": "^0.9.2",
    "log4js": "^2.3.3",
    "morgan": "~1.7.0",
    "node-cache": "^4.1.1",
    "node-fetch": "^1.6.3",
    "node-sass": "^4.7.2",
    "serve-favicon": "~2.3.2"
  },
  "devDependencies": {
    "@babel/plugin-transform-runtime": "^7.0.0-beta.47",
    "@babel/preset-stage-0": "^7.0.0-beta.47",
    "babel-plugin-import": "^1.8.0",
    "babel-plugin-module-resolver": "^3.1.1",
    "babel-plugin-react-css-modules": "^3.4.2",
    "body-parser": "^1.18.2",
    "docz": "^0.2.11",
    "docz-plugin-css": "^0.2.11",
    "eslint-plugin-html": "^3.2.0",
    "sass-lint": "^1.10.2"
  }
}
```

**Comment by pedronauck** [comment]
try to update docz please @vpsouza... looking over your package.json there's nothing wrong, all these babel modules are compatible with babel@7?

**Comment by pedronauck** [comment]
Sorry the too late reply @vpsouza, but is kinda impossible to work with `webpack < 4` with docz. We're using webpack 4 because it resolves a lot of performance issues 😢
